Changed yml to erb for correct port mapping, updated control file

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -9,16 +9,14 @@ function _install_copy_jar() {
  
   files=($OPENSHIFT_REPO_DIR/*.jar)
 
-  if [ -e "${files[0]}" ];
+  if [ ${#files[@]} -eq 0 ];
   then
     echo "No jar files found"
-    ##exit 1
+    exit 1
   fi
 
-  echo "Installing JAR to launch service..."
+  echo "Copying JAR to launch service..."
   cp $OPENSHIFT_REPO_DIR/*.jar $OPENSHIFT_DATA_DIR/build.jar
-  sed -i 's/@OPENSHIFT_INTERNAL_IP@/'"$OPENSHIFT_DWIZARD_IP"'/g' $OPENSHIFT_REPO_DIR/hello-world.yml
-
 }
 
 function _is_running() {
@@ -43,7 +41,12 @@ function start() {
   export PUBLISH_HOST=$(python -c "import socket; print socket.gethostbyname('$OPENSHIFT_GEAR_DNS')")
 
   java -jar $OPENSHIFT_DATA_DIR/build.jar server $OPENSHIFT_REPO_DIR/helloworld.yml > $OPENSHIFT_DWIZARD_DIR/logs/helloworld.log 2>&1 &
+  if [ $? -ne 0 ]; then
+     echo "Dropwizard failed to start"
+     exit 1
+  fi
   echo "$!" > $PID_FILE
+  echo "Dropwizard running"
 }
 
 function stop() {
